extends:
  - eslint:recommended
  - airbnb-base
  - plugin:prettier/recommended
env:
  es6: true
  node: true
  jest: true
rules:
  no-console: 'off'
  no-plusplus: 'off'
  no-param-reassign: ['error', { props: false }]
  class-methods-use-this: 'off'
  semi: 'off'
  no-nested-ternary: 'off'
  curly: [ 'error', 'all' ]
